### ISSUE TITLE
config.yml not found when executing doctl commands - default path corrupted

### ISSUE THREAD

**Issue by lu-roth** [digitalocean/doctl#1280]
When executing doctl commands I get the following error:
Error: open : no such file or directory

Thats because the default path of the config.yaml is corrupted and the blank space betweet "Application Support" is not escaped like it should be "Application\ Support". 

current: ${HOME}/Library/Application Support/doctl/config.yaml
should be: ${HOME}/Library/Application\ Support/doctl/config.yaml

After adding the "--config" option and setting the config path by myself the doctl commands work but I think its tedious
to do this for every command.

**Environment:**

 - doctl version: 1.83.0
 - OS: macOS Monterey
 - Installation method: Installed from source (doctl-1.83.0-darwin-arm64.tar.gz)

**Comment by andrewsomething** [comment]
Hi @lu-roth,

Thanks for flagging this for us. We have not been able to reproduce the issue ourselves. Can you help by providing some additional information?

- Is the variable `DIGITALOCEAN_CONFIG` set in the environment?
- What shell are you using?
- What terminal emulator are you using?
- Is there anything unique about your environment that we should know?

**Comment by lu-roth** [comment]
Hi @andrewsomething 

- No, DIGITALOCEAN_CONFIG is not set when doing `printenv`
- The `doctl --help` outputs as default for the `--config` flag: `${HOME}/Library/Application Support/doctl/config.yaml`
- I am using `zsh` as shell
- I'm using iTerm2 as terminal emulator (https://iterm2.com/)
- No nothing special about my environment

Other people reported the same issue in a different issue, maybe the comment section will provide you more clarity: 
https://github.com/digitalocean/doctl/issues/604

**Comment by andrewsomething** [comment]
I believe we have tracked down the root of this problem. It should be fixed in the [v1.84.0 release](https://github.com/digitalocean/doctl/releases/tag/v1.84.0) via https://github.com/digitalocean/doctl/pull/1286. Unfortunately, the issue was with the config file itself. So if you have been experiencing this problem, you will need to either delete your existing config file or edit it to remove the stanza that looks like:

```
config:
  set:
    dev-config: ""
```

Please let us know if this has resolved the issue for you.

**Comment by grantkee** [comment]
Still having this issue with version 1.92.1-release installed on MacOS using homebrew
