### ISSUE TITLE
doctl apps logs follow mode unexpectedly exits

### ISSUE THREAD

**Issue by Craytor** [digitalocean/doctl#954]
**Describe the Issue:**
When I run `doctl apps logs c2ad307c-6f44-43f5-9b89-a80909b03e3d -f`, doctl will get all the current logs and print them to the terminal. However, doctl does not follow the logs as intended with `-f`. doctl will wait about a minute and then exit the log listening process.

**Environment:**
 - doctl version: doctl version 1.56.0-release
 - OS: macOS Catalina
 - Installation method: Homebrew

**Additional Details:**
Not sure of any - if there are any questions please let me know and I can assist.

**Comment by andrewsomething** [comment]
Thanks for raising this issue @Craytor We've just release v1.57.0 which should resolve this issue.

**Comment by fedebaier** [comment]
I'm running v1.57.0 on macOS Big Sur, installed with Homebrew, and this is still happening.
